Replace `npm run` with `yarn` because it handles workspaces better
❯ yarn build.es2015
yarn run v1.22.4
warning package.json: No license field
$ ngc -p tsconfig.json && rollup --config ./scripts/rollup.config.js
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(2,24): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(2,31): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(3,27): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(3,34): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(4,29): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(4,36): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(5,32): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(5,39): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(7,16): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(7,18): error TS1128: Declaration or statement expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(7,34): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(8,14): error TS1005: ',' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(8,23): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(8,25): error TS1128: Declaration or statement expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(8,41): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(10,29): error TS1005: ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(10,36): error TS1011: An element access expression should take an argument.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(11,1): error TS1128: Declaration or statement expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(12,92): error TS1144: '{' or ';' expected.
../../node_modules/next/dist/next-server/server/get-page-files.d.ts(12,99): error TS1011: An element access expression should take an argument.