chore: upgrade tslib to 2.0
upgrade is required to workaround build error:
src/Logger/ConsoleLogger.ts(134,28): error TS2343: This syntax
requires an imported helper named '__spreadArray' which does not
exist in 'tslib'. Consider upgrading your version of 'tslib'.